version: '3.5'

services:

  django:
    restart: 'no'
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    container_name: django
    ports:
    - "8000:8000"

  grafana:
    image: grafana/grafana
    ports:
      - "3060:3000"
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
